default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_general_ci
  pool: 5
  username: root
  password: password
  host: localhost
  port: 3306

development:
  <<: *default
  database: telegram_bot_development